/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {

  "aws_project_region": "us-east-2",
  "aws_cognito_identity_pool_id": "us-east-2:4b8d0d6b-7935-4f2b-b722-b039d224d1b8",
  "aws_cognito_region": "us-east-2",
  "aws_user_pools_id": "us-east-2_86XipuLMN",
  "aws_user_pools_web_client_id": "1jj5vtvojpi3k81esuk14mis17",
  "oauth": {},
  "aws_cognito_username_attributes": [],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
      "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
      "SMS"
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ],
  "aws_user_files_s3_bucket": "polp-media",
  "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;

