import Head from "next/head";
import { Inter } from "@next/font/google";
import NavBar from "@/components/NavBar";
import PageTitle from "@/components/PageTitle";
import { useAuthenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";
import MediaContext from "@/components/MediaContext";
import { useContext } from "react";
import Feed from "@/components/Feed";
import ControlBar from "@/components/ControlBar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { user, signOut } = useAuthenticator((context) => [context.user]);

  return (
    <>
      <Head>
        <title>POLP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className="h-screen bg-cream">
        <NavBar />
        <PageTitle />
        <Feed />
        <ControlBar />
      </main>
    </>
  );
}
