/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": process.env.NEXT_PUBLIC_AWS_COGNITO_IDENTITY_POOL_ID,
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": process.env.NEXT_PUBLIC_AWS_USER_POOLS_ID,
    "aws_user_pools_web_client_id": process.env.NEXT_PUBLIC_AWS_USER_POOLS_WEB_CLIENT_ID,
    "oauth": {
        "domain": "polp-user-pool.auth.us-east-2.amazoncognito.com",
        "scope": ["email", "openid", "profile","aws.cognito.signin.user.admin"],
        "redirectSignIn": process.env.NEXT_PUBLIC_REDIRECT_SIGN_IN,
        "redirectSignOut": process.env.NEXT_PUBLIC_REDIRECT_SIGN_OUT,
        "responseType": 'code', // or 'token'
        "googleClientId": process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
      },
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": process.env.NEXT_PUBLIC_AWS_USER_FILES_S3_BUCKET,
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
